AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/features/**/*'

Metrics/LineLength:
  Max: 100
