AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/features/**/*'

Metrics/LineLength:
  Max: 100
