# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb615fe0a699e3d320dffeaca954784a863ba7e327cc5792b6411c6cbbd635ca0ecb8e022b1e7c8f7d44dc622174d47e9ccf9cd199eab967d7fc8f063ae02b66

test:
  secret_key_base: fc71e9c9acf424a73e42a8f2e0eb9f07f7b68434f5dac8a50d094bf15149a896a1c36588db0b7cdc80302450fca39757c233a40f6fb80006ab91c94c056003ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
